name: Format Code

on:
  push:
    branches:
      - feature/store-jwt-in-cookies/mo
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract The NodeJs Version From .tool-versions File
        id: extract_node_version
        run: |
          NODE_VERSION=$(grep -i 'nodejs' .tool-versions | awk '{print $2}')
          echo "::set-output name=node-version::$NODE_VERSION"
        shell: bash

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.extract_node_version.outputs.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Run Prettier
        run: npx prettier --write .

      - name: Commit and Push Code
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Format the Code"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
